### ISSUE TITLE
Missing moz.build file

### ISSUE THREAD

**Issue by HarvHouHacker** [HarvHouHacker/Light-Web-Browser#8]
I'm having trouble building Firefox because of a missing moz.build file. I get this error after running `./mach build`:
```
 0:07.02 Creating config.status
 0:07.15 Reticulating splines...
 0:13.55 Traceback (most recent call last):
 0:13.55   File "$HOMEDIR$/firefox-53.0/configure.py", line 124, in <module>
 0:13.55     sys.exit(main(sys.argv))
 0:13.55   File "$HOMEDIR$/firefox-53.0/configure.py", line 34, in main
 0:13.55     return config_status(config)
 0:13.55   File "$HOMEDIR$/firefox-53.0/configure.py", line 119, in config_status
 0:13.55     return config_status(args=[], **encode(sanitized_config, encoding))
 0:13.55   File "$HOMEDIR$/firefox-53.0/python/mozbuild/mozbuild/config_status.py", line 147, in config_status
 0:13.55     definitions = list(definitions)
 0:13.55   File "$HOMEDIR$/firefox-53.0/python/mozbuild/mozbuild/frontend/emitter.py", line 169, in emit
 0:13.55     for out in output:
 0:13.55   File "$HOMEDIR$/firefox-53.0/python/mozbuild/mozbuild/frontend/reader.py", line 917, in read_topsrcdir
 0:13.55     for r in self.read_mozbuild(path, self.config):
 0:13.55   File "$HOMEDIR$/firefox-53.0/python/mozbuild/mozbuild/frontend/reader.py", line 1090, in read_mozbuild
 0:13.56     raise bre
 0:13.56 mozbuild.frontend.reader.BuildReaderError:
 0:13.56 ==============================
 0:13.56 ERROR PROCESSING MOZBUILD FILE
 0:13.56 ==============================
 0:13.56 
 0:13.56 The error occurred while processing the following file:
 0:13.56 
 0:13.56     $HOMEDIR$/firefox-53.0/toolkit/components/moz.build
 0:13.56 
 0:13.56 The underlying problem is we referenced a path that does not exist. That path is:
 0:13.56 
 0:13.56     $HOMEDIR$/firefox-53.0/toolkit/components/social/moz.build
 0:13.56 
 0:13.56 Either create the file if it needs to exist or do not reference it.
 0:13.56 
 0:13.69 *** Fix above errors and then restart with\
 0:13.69                "/usr/bin/make -f client.mk build"
 0:13.69 $HOMEDIR$/firefox-53.0/client.mk:379: recipe for target 'configure' failed
 0:13.69 make[2]: *** [configure] Error 1
 0:13.69 $HOMEDIR$/firefox-53.0/client.mk:396: recipe for target '$HOMEDIR$/firefox-53.0/obj-x86_64-pc-linux-gnu/Makefile' failed
 0:13.69 make[1]: *** [$HOMEDIR$/firefox-53.0/obj-x86_64-pc-linux-gnu/Makefile] Error 2
 0:13.69 client.mk:170: recipe for target 'build' failed
 0:13.69 make: *** [build] Error 2
 0:13.73 0 compiler warnings present.
```
This was after applying the patches. Still, the file is indeed missing.

**Comment by HarvHouHacker** [comment]
Herm, not all the patches were applied. Perhaps i should have used > instead of <?

**Comment by HarvHouHacker** [comment]
Closing issue for now. I've switched to Firefox 53.0.3. If I run across this error again, I'll reopen this issue.

**Comment by HarvHouHacker** [comment]
Haven't run across this in a while, so I'll lock it for now.
